import { z } from "zod";

const jobStatusEnum = [
  'unassigned',
  'assigned',
  'dispatched',
  'on_the_way',
  'arrived',
  'passenger_on_board',
  'passenger_dropped_off',
  'done'
] as const;

export const bookingFormSchema = z.object({
  id: z.number().optional(),
  createdAt: z.date().nullable().optional(),
  updatedAt: z.date().nullable().optional(),
  basePrice: z.string(),
  categoryId: z.number().nullable().optional(),
  userId: z.number().optional(),
  tripId: z.string(),
  accountId: z.string().nullable().optional(),
  billingContact: z.string().nullable().optional(),
  companyName: z.string().nullable().optional(),
  passengerFirstName: z.string(),
  passengerLastName: z.string(),
  passengerPhone: z.string(),
  passengerEmail: z.string(),
  poClientRef: z.string().nullable().optional(),
  pickupDate: z.date(),
  pickupTime: z.string(),
  pickupLocation: z.string(),
  dropoffLocation: z.string(),
  airportCode: z.string().nullable().optional(),
  airportName: z.string().nullable().optional(),
  airlineCode: z.string().nullable().optional(),
  airlineName: z.string().nullable().optional(),
  flightNumber: z.string().nullable().optional(),
  tripNotes: z.string().nullable().optional(),
  jobStatus: z.enum(jobStatusEnum).default('unassigned'),
  additionalRequests: z.array(z.string()).default([]),
  serviceType: z.string(),
  vehicleType: z.string(),
  chauffeurId: z.number().nullable().optional(),
  vehicleId: z.number().nullable().optional(),
  gratuityFee: z.string().default('0'),
  extraStopsFee: z.string().default('0'),
  discount: z.string().default('0'),
  tolls: z.string().default('0'),
  parking: z.string().default('0'),
  creditCardFee: z.string().default('0'),
  grandTotal: z.string(),
  paymentsDeposits: z.string().default('0'),
  totalDue: z.string(),
  trackingEnabled: z.boolean().default(false),
  lastKnownLatitude: z.number().nullable().optional(),
  lastKnownLongitude: z.number().nullable().optional(),
  lastLocationUpdate: z.date().nullable().optional(),
  estimatedArrivalTime: z.date().nullable().optional(),
  driverName: z.string().optional(),
});

export type BookingFormData = z.infer<typeof bookingFormSchema>;

export const jobStatusOptions = jobStatusEnum;
