import { z } from "zod";

export const bookingFormSchema = z.object({
  id: z.number().optional(),
  createdAt: z.date().nullable().optional(),
  updatedAt: z.date().nullable().optional(),
  basePrice: z.string(),
  categoryId: z.number().nullable().optional(),
  userId: z.string().optional(),
  tripId: z.string(),
  accountId: z.string().nullable().optional(),
  billingContact: z.string().nullable().optional(),
  companyName: z.string().nullable().optional(),
  passengerFirstName: z.string(),
  passengerLastName: z.string(),
  passengerPhone: z.string(),
  passengerEmail: z.string(),
  poClientRef: z.string().nullable().optional(),
  pickupDate: z.date(),
  pickupTime: z.string(),
  pickupLocation: z.string(),
  dropoffLocation: z.string(),
  airportCode: z.string().nullable().optional(),
  airportName: z.string().nullable().optional(),
  airlineCode: z.string().nullable().optional(),
  airlineName: z.string().nullable().optional(),
  flightNumber: z.string().nullable().optional(),
  tripNotes: z.string().nullable().optional(),
  jobStatus: z.string().nullable().optional(),
  additionalRequests: z.array(z.string()).nullable().optional(),
  serviceType: z.string(),
  vehicleType: z.string(),
  chauffeurId: z.number().nullable().optional(),
  vehicleId: z.number().nullable().optional(),
  gratuityFee: z.string().optional(),
  extraStopsFee: z.string().optional(),
  discount: z.string().optional(),
  tolls: z.string().optional(),
  parking: z.string().optional(),
  creditCardFee: z.string().optional(),
  grandTotal: z.string().optional(),
  paymentsDeposits: z.string().optional(),
  totalDue: z.string().optional(),
  trackingEnabled: z.boolean().optional(),
  lastKnownLatitude: z.number().nullable().optional(),
  lastKnownLongitude: z.number().nullable().optional(),
  lastLocationUpdate: z.date().nullable().optional(),
  estimatedArrivalTime: z.date().nullable().optional(),
  driverName: z.string().optional(),
});

export type BookingFormData = z.infer<typeof bookingFormSchema>;
